test.todo('deve aplicar mascara caso ocorra paste de 00000000000');
test.todo('deve aplicar mascara caso ocorra paste de (00) 00000-0000');
test.todo('deve aplicar mascara quando usuário estiver digitando');
test.todo('deve inicializar com valor zerado');
test.todo('deve possibilitar a renderização de mais de um input do mesmo tipo');
test.todo('deve aplicar foco no input caso label seja selecionado');
test.todo('deve exibir mensagem de inválido');
test.todo('deve renderizar conteúdo do label conforme parametro');
test.todo('deve desabilitar o input');
test.todo('deve executar o onChange');
test.todo('deve exibir * quando input for exigido');
